<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * shopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shopRepository extends EntityRepository
{
    public function getByBorders(int $firstElement, int $items)
    {

        return $this->getEntityManager()->createQuery(
            'SELECT s FROM ShopBundle:Shops s'
        )
            ->setFirstResult($firstElement-1)
            ->setMaxResults($items)
            ->getResult();
    }

}
