<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * shop_reviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shop_reviewsRepository extends EntityRepository
{
    public function getByShop(int $shopId, string $password)
    {
        $now = new \DateTime();
        return $this->getEntityManager()->createQuery(
            'SELECT r.review FROM ShopBundle:ShopReviews r WHERE r.fkShop=:shopId AND r.hash=:password'
        )->setParameter('shopId',$shopId)
            ->setParameter('password',$password)
            ->getResult();
    }
}
