<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * shop_reviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shop_reviewsRepository extends EntityRepository
{
    public function getByShop(int $shopId, string $password, int $limit)
    {
        $pw = $this->getEntityManager()->createQuery('SElECT s.id from ShopBundle:Shops s WHERE s.id=:id AND s.interfacePassword=:pw')
            ->setParameter('id', $shopId)
        ->setParameter('pw', $password)
        ->getResult();

        return $this->getEntityManager()->createQuery(
            'SELECT r.review FROM ShopBundle:ShopReviews r WHERE r.fkShop=:shopId'
        )->setParameter('shopId',$pw)
            ->setMaxResults($limit)
            ->getResult();
    }
}
